kind: Deployment
apiVersion: apps/v1
metadata:
    labels:
        app: springhellowweb
    name: springhellowweb
    namespace: app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: springhellowweb
    template:
        metadata:
            labels:
                app: springhellowweb
        spec:
            containers:
              - image: springboothelloweb/springhellowweb:0.0.1
                imagePullPolicy: IfNotPresent
                name: springhellowweb
                resources:
                  requests:
                    memory: "128Mi"
                    cpu: "250m"
                  limits:
                    memory: "256Mi"
                    cpu: "500m"
